name: openmedkit_flutter
description: Local-first Flutter FFI bindings for OpenMed token classification.
version: 0.1.0
homepage: https://github.com/maziyarpanahi/openmed
repository: https://github.com/maziyarpanahi/openmed
publish_to: none

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ">=1.1.2 <3.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: org.openmed.openmedkit.flutter
        pluginClass: OpenMedKitFlutterPlugin
      ios:
        pluginClass: OpenMedKitFlutterPlugin
      linux:
        pluginClass: OpenMedKitFlutterPlugin
      macos:
        pluginClass: OpenMedKitFlutterPlugin
      windows:
        pluginClass: OpenMedKitFlutterPlugin
